### ISSUE TITLE
Converting ply data to STEP format

### ISSUE THREAD

**Issue by jxxtin** [QiujieDong/NeurCADRecon#3]
Thank you for your amazing work.

Can I save files in STEP format instead of Ply format?

**Comment by QiujieDong** [comment]
> Thank you for your amazing work.
> 
> Can I save files in STEP format instead of Ply format?


Hi, @jxxtin,

we save the output files using trimesh.
The supported formats of trimesh are stl, off, ply, collada, json, dict, glb, dict64, msgpack.

Best Regards
