### ISSUE TITLE
Dynamic Sampling

### ISSUE THREAD

**Issue by Xiaoyanglib** [QiujieDong/NeurCADRecon#4]
Thank you very much for your amazing work!
I'm interested in the dynamic sampling in the paper, could you please tell me what part of the code the dynamic sampling corresponds to?

**Comment by QiujieDong** [comment]
> Thank you very much for your amazing work! I'm interested in the dynamic sampling in the paper, could you please tell me what part of the code the dynamic sampling corresponds to?

Hi, Xiaoyang,


The code of dynamic sampling is:
```
grad = points_grad / (points_grad .norm(dim=-1) + 1e-12)[:, :, None]
points_map = points - grad * output_pred['points_pred']
```
You can use this code to map the near or non-manifold points by changing ''points'' to the points you want to process.

Best Regards,
Qiujie

**Comment by Xiaoyanglib** [comment]
Thank you for the explanation! But I don't seem to find this code in the current code repository... Are the non-manifold points here including all the points in the bounding box points set Q and update to Q' at each epoch?

**Comment by Xiaoyanglib** [comment]
> > Thank you very much for your amazing work! I'm interested in the dynamic sampling in the paper, could you please tell me what part of the code the dynamic sampling corresponds to?
> 
> Hi, Xiaoyang,
> 
> The code of dynamic sampling is:
> 
> ```
> grad = points_grad / (points_grad .norm(dim=-1) + 1e-12)[:, :, None]
> points_map = points - grad * output_pred['points_pred']
> ```
> 
> You can use this code to map the near or non-manifold points by changing ''points'' to the points you want to process.
> 
> Best Regards, Qiujie

Thank you for the explanation! But I don't seem to find this code in the current code repository... Are the non-manifold points here including all the points in the bounding box points set Q and update to Q' at each epoch?

**Comment by QiujieDong** [comment]
> > > Thank you very much for your amazing work! I'm interested in the dynamic sampling in the paper, could you please tell me what part of the code the dynamic sampling corresponds to?
> > 
> > 
> > Hi, Xiaoyang,
> > The code of dynamic sampling is:
> > ```
> > grad = points_grad / (points_grad .norm(dim=-1) + 1e-12)[:, :, None]
> > points_map = points - grad * output_pred['points_pred']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can use this code to map the near or non-manifold points by changing ''points'' to the points you want to process.
> > Best Regards, Qiujie
> 
> Thank you for the explanation! But I don't seem to find this code in the current code repository... Are the non-manifold points here including all the points in the bounding box points set Q and update to Q' at each epoch?


Hi, Xiaoyang,

In the experiment, dynamic sampling started from epoch 5000.

**Comment by Xiaoyanglib** [comment]
> > > > Thank you very much for your amazing work! I'm interested in the dynamic sampling in the paper, could you please tell me what part of the code the dynamic sampling corresponds to?
> > > 
> > > 
> > > Hi, Xiaoyang,
> > > The code of dynamic sampling is:
> > > ```
> > > grad = points_grad / (points_grad .norm(dim=-1) + 1e-12)[:, :, None]
> > > points_map = points - grad * output_pred['points_pred']
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can use this code to map the near or non-manifold points by changing ''points'' to the points you want to process.
> > > Best Regards, Qiujie
> > 
> > 
> > Thank you for the explanation! But I don't seem to find this code in the current code repository... Are the non-manifold points here including all the points in the bounding box points set Q and update to Q' at each epoch?
> 
> Hi, Xiaoyang,
> 
> In the experiment, dynamic sampling started from epoch 5000.

Hi Qiujie,

I read in the paper that the annealing factor 𝜏 decreases to 1e-4 at epoch 5000 (if the total number of epochs is 10000). And dynamic sampling enables L_Gauss to more effectively guide the surface's evolution. If dynamic sampling starts at epoch 5000, can 𝜏 × λ_Gauss × L_Gauss still effectively guide the surface's evolution?

**Comment by QiujieDong** [comment]
> > > > > Thank you very much for your amazing work! I'm interested in the dynamic sampling in the paper, could you please tell me what part of the code the dynamic sampling corresponds to?
> > > > 
> > > > 
> > > > Hi, Xiaoyang,
> > > > The code of dynamic sampling is:
> > > > ```
> > > > grad = points_grad / (points_grad .norm(dim=-1) + 1e-12)[:, :, None]
> > > > points_map = points - grad * output_pred['points_pred']
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > You can use this code to map the near or non-manifold points by changing ''points'' to the points you want to process.
> > > > Best Regards, Qiujie
> > > 
> > > 
> > > Thank you for the explanation! But I don't seem to find this code in the current code repository... Are the non-manifold points here including all the points in the bounding box points set Q and update to Q' at each epoch?
> > 
> > 
> > Hi, Xiaoyang,
> > In the experiment, dynamic sampling started from epoch 5000.
> 
> Hi Qiujie,
> 
> I read in the paper that the annealing factor 𝜏 decreases to 1e-4 at epoch 5000 (if the total number of epochs is 10000). And dynamic sampling enables L_Gauss to more effectively guide the surface's evolution. If dynamic sampling starts at epoch 5000, can 𝜏 × λ_Gauss × L_Gauss still effectively guide the surface's evolution?

Hi, Xiaoyang,

At the 5K epoch, the annealing factor is 1e-4, but the weight of L_Gauss is 1e-3 because the weight equals the annealing factor multiplied by the initial weight. It can guide the evolution of the surface.

Qiujie

**Comment by Xiaoyanglib** [comment]
> > > > > > Thank you very much for your amazing work! I'm interested in the dynamic sampling in the paper, could you please tell me what part of the code the dynamic sampling corresponds to?
> > > > > 
> > > > > 
> > > > > Hi, Xiaoyang,
> > > > > The code of dynamic sampling is:
> > > > > ```
> > > > > grad = points_grad / (points_grad .norm(dim=-1) + 1e-12)[:, :, None]
> > > > > points_map = points - grad * output_pred['points_pred']
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > You can use this code to map the near or non-manifold points by changing ''points'' to the points you want to process.
> > > > > Best Regards, Qiujie
> > > > 
> > > > 
> > > > Thank you for the explanation! But I don't seem to find this code in the current code repository... Are the non-manifold points here including all the points in the bounding box points set Q and update to Q' at each epoch?
> > > 
> > > 
> > > Hi, Xiaoyang,
> > > In the experiment, dynamic sampling started from epoch 5000.
> > 
> > 
> > Hi Qiujie,
> > I read in the paper that the annealing factor 𝜏 decreases to 1e-4 at epoch 5000 (if the total number of epochs is 10000). And dynamic sampling enables L_Gauss to more effectively guide the surface's evolution. If dynamic sampling starts at epoch 5000, can 𝜏 × λ_Gauss × L_Gauss still effectively guide the surface's evolution?
> 
> Hi, Xiaoyang,
> 
> At the 5K epoch, the annealing factor is 1e-4, but the weight of L_Gauss is 1e-3 because the weight equals the annealing factor multiplied by the initial weight. It can guide the evolution of the surface.
> 
> Qiujie

Hi Qiujie,

You're so warm-hearted! Thank you very much for answering my questions, and I learned a lot.

Xiaoyang.
